; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-linux-gnu -code-model=large -relocation-model=pic -aarch64-min-jump-table-entries=4 -o - %s | FileCheck %s

; The large position-independent code model reaches preemptible symbols through
; the GOT, indexing it with a full 64-bit offset, and reaches local symbols
; directly with a full 64-bit PC-relative displacement. Neither uses ADRP, whose
; +/-4GB range is what the large code model exists to escape.

@preemptible = external global i32
@local = dso_local global i32 0

define i32 @load_preemptible() {
; CHECK-LABEL: load_preemptible:
; CHECK:       // %bb.0:
; CHECK-NEXT:    movz x8, #:gotoff_g0_nc:preemptible
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    adr x9, .Ltmp0
; CHECK-NEXT:    movz x17, #:prel_g3:_GLOBAL_OFFSET_TABLE_+4
; CHECK-NEXT:    movk x17, #:prel_g2_nc:_GLOBAL_OFFSET_TABLE_+8
; CHECK-NEXT:    movk x17, #:prel_g1_nc:_GLOBAL_OFFSET_TABLE_+12
; CHECK-NEXT:    movk x17, #:prel_g0_nc:_GLOBAL_OFFSET_TABLE_+16
; CHECK-NEXT:    add x9, x9, x17
; CHECK-NEXT:    movk x8, #:gotoff_g1_nc:preemptible
; CHECK-NEXT:    movk x8, #:gotoff_g2_nc:preemptible
; CHECK-NEXT:    movk x8, #:gotoff_g3:preemptible
; CHECK-NEXT:    ldr x8, [x9, x8]
; CHECK-NEXT:    ldr w0, [x8]
; CHECK-NEXT:    ret
  %v = load i32, ptr @preemptible
  ret i32 %v
}

define i32 @load_local() {
; CHECK-LABEL: load_local:
; CHECK:       // %bb.0:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    adr x8, .Ltmp1
; CHECK-NEXT:    movz x17, #:prel_g3:.Llocal$local+4
; CHECK-NEXT:    movk x17, #:prel_g2_nc:.Llocal$local+8
; CHECK-NEXT:    movk x17, #:prel_g1_nc:.Llocal$local+12
; CHECK-NEXT:    movk x17, #:prel_g0_nc:.Llocal$local+16
; CHECK-NEXT:    add x8, x8, x17
; CHECK-NEXT:    ldr w0, [x8]
; CHECK-NEXT:    ret
  %v = load i32, ptr @local
  ret i32 %v
}

; The GOT base is a separate node so that repeated GOT accesses in one function
; share a single computation of it.
define i32 @two_got_accesses(ptr %p) {
; CHECK-LABEL: two_got_accesses:
; CHECK:       // %bb.0:
; CHECK-NEXT:    movz x8, #:gotoff_g0_nc:preemptible
; CHECK-NEXT:    movz x9, #:gotoff_g0_nc:other
; CHECK-NEXT:    movk x8, #:gotoff_g1_nc:preemptible
; CHECK-NEXT:    movk x9, #:gotoff_g1_nc:other
; CHECK-NEXT:    movk x8, #:gotoff_g2_nc:preemptible
; CHECK-NEXT:    movk x9, #:gotoff_g2_nc:other
; CHECK-NEXT:    movk x8, #:gotoff_g3:preemptible
; CHECK-NEXT:    movk x9, #:gotoff_g3:other
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    adr x10, .Ltmp2
; CHECK-NEXT:    movz x17, #:prel_g3:_GLOBAL_OFFSET_TABLE_+4
; CHECK-NEXT:    movk x17, #:prel_g2_nc:_GLOBAL_OFFSET_TABLE_+8
; CHECK-NEXT:    movk x17, #:prel_g1_nc:_GLOBAL_OFFSET_TABLE_+12
; CHECK-NEXT:    movk x17, #:prel_g0_nc:_GLOBAL_OFFSET_TABLE_+16
; CHECK-NEXT:    add x10, x10, x17
; CHECK-NEXT:    ldr x8, [x10, x8]
; CHECK-NEXT:    ldr x9, [x10, x9]
; CHECK-NEXT:    ldr w8, [x8]
; CHECK-NEXT:    ldr w9, [x9]
; CHECK-NEXT:    add w0, w8, w9
; CHECK-NEXT:    ret
  %a = load i32, ptr @preemptible
  %b = load i32, ptr @other
  %s = add i32 %a, %b
  ret i32 %s
}

@other = external global i32

; Jump tables, constant pools and block addresses are all module-local, so they
; need a full-range address but never GOT indirection.

declare void @g0()
declare void @g1()
declare void @g2()
declare void @g3()
declare void @g4()

define void @jump_table(i32 %x) {
; CHECK-LABEL: jump_table:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmp w0, #4
; CHECK-NEXT:    b.hi .LBB3_7
; CHECK-NEXT:  // %bb.1: // %entry
; CHECK-NEXT:    mov w8, w0
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    adr x9, .Ltmp3
; CHECK-NEXT:    movz x17, #:prel_g3:.LJTI3_0+4
; CHECK-NEXT:    movk x17, #:prel_g2_nc:.LJTI3_0+8
; CHECK-NEXT:    movk x17, #:prel_g1_nc:.LJTI3_0+12
; CHECK-NEXT:    movk x17, #:prel_g0_nc:.LJTI3_0+16
; CHECK-NEXT:    add x9, x9, x17
; CHECK-NEXT:    adr x10, .LBB3_2
; CHECK-NEXT:    ldrb w11, [x9, x8]
; CHECK-NEXT:    add x10, x10, x11, lsl #2
; CHECK-NEXT:    br x10
; CHECK-NEXT:  .LBB3_2: // %c0
; CHECK-NEXT:    b g0
; CHECK-NEXT:  .LBB3_3: // %c4
; CHECK-NEXT:    b g4
; CHECK-NEXT:  .LBB3_4: // %c2
; CHECK-NEXT:    b g2
; CHECK-NEXT:  .LBB3_5: // %c3
; CHECK-NEXT:    b g3
; CHECK-NEXT:  .LBB3_6: // %c1
; CHECK-NEXT:    b g1
; CHECK-NEXT:  .LBB3_7: // %common.ret
; CHECK-NEXT:    ret
entry:
  switch i32 %x, label %def [ i32 0, label %c0
                              i32 1, label %c1
                              i32 2, label %c2
                              i32 3, label %c3
                              i32 4, label %c4 ]
c0:  tail call void @g0() ret void
c1:  tail call void @g1() ret void
c2:  tail call void @g2() ret void
c3:  tail call void @g3() ret void
c4:  tail call void @g4() ret void
def: ret void
}

define double @constant_pool(double %x) {
; CHECK-LABEL: constant_pool:
; CHECK:       // %bb.0:
; CHECK-NEXT:  .Ltmp4:
; CHECK-NEXT:    adr x8, .Ltmp4
; CHECK-NEXT:    movz x17, #:prel_g3:.LCPI4_0+4
; CHECK-NEXT:    movk x17, #:prel_g2_nc:.LCPI4_0+8
; CHECK-NEXT:    movk x17, #:prel_g1_nc:.LCPI4_0+12
; CHECK-NEXT:    movk x17, #:prel_g0_nc:.LCPI4_0+16
; CHECK-NEXT:    add x8, x8, x17
; CHECK-NEXT:    ldr d1, [x8]
; CHECK-NEXT:    fadd d0, d0, d1
; CHECK-NEXT:    ret
  %r = fadd double %x, 3.14159265358979
  ret double %r
}

define ptr @block_address() {
; CHECK-LABEL: block_address:
; CHECK:       // %bb.0:
; CHECK-NEXT:  .Ltmp6:
; CHECK-NEXT:    adr x0, .Ltmp6
; CHECK-NEXT:    movz x17, #:prel_g3:.Ltmp5+4
; CHECK-NEXT:    movk x17, #:prel_g2_nc:.Ltmp5+8
; CHECK-NEXT:    movk x17, #:prel_g1_nc:.Ltmp5+12
; CHECK-NEXT:    movk x17, #:prel_g0_nc:.Ltmp5+16
; CHECK-NEXT:    add x0, x0, x17
; CHECK-NEXT:    ret
  ret ptr blockaddress(@block_address_target, %there)
}

define void @block_address_target(i1 %c) {
; CHECK-LABEL: block_address_target:
; CHECK:       // %bb.0:
; CHECK-NEXT:  .Ltmp5: // Block address taken
; CHECK-NEXT:  // %bb.1: // %common.ret
; CHECK-NEXT:    ret
  br i1 %c, label %there, label %here
here:
  ret void
there:
  ret void
}
